### ISSUE TITLE
Include fa-rss again

### ISSUE THREAD

**Issue by fte378** [alanorth/hugo-theme-bootstrap4-blog#40]
Hi Alan,

I  want to "misuse" the "about" sidebar section to display a link to my RSS feed.
I remember that you stripped down font-awesome to the needed symbols.

Can you pleas eadd the rss icons again? That would be fa-rss and fa-rss-square.

Many thanks!

**Comment by alanorth** [comment]
Done! Added both `fa-rss` and `fa-rss-square`.

**Comment by fte378** [comment]
Many thanks!

**Comment by fte378** [comment]
Is there something needed to generate some files?
I still don't get the symbol. The facebook and Google+ symbols appear, so it's something with the font setup.

Btw. I found a service to reduce the font files also (if not done already): www.fontello.com

**Comment by alanorth** [comment]
How are you calling `fa-rss`? It must be HTML (and all HTML is valid Markdown, by definition). For example, I add this to my `about`:

```
about = "... <span class=\"fa fa-rss fa-2x\"></span> ..."
```

And I get this:

![screen shot 2017-01-08 at 17 02 28-fs8](https://cloud.githubusercontent.com/assets/191754/21750803/6c4f6962-d5c4-11e6-9f69-c9afcf339667.png)

I don't want to use a web service like fontello.com to reduce the font files because that is an external process—I want to keep everything in the source repository so that it is documented and repeatable with free, open-source tools. If I get hit by a bus there is no process or knowledge in my head that gets lost and someone can continue developing the theme. ;)

**Comment by fte378** [comment]
`about = "<a href=\"/index.xml\" title=\"RSS\"><i class=\"fa fa-rss fa-2x\" aria-hidden=\"true\"></i> RSS-Feed</a>"`

And I overwrite sidebar.partial to remove the About headline. Maybe there is a css mismatch then?
But as I said: with fa-facebook and fa-google-plus it works.

**Comment by alanorth** [comment]
Works for me with your code!

![screen shot 2017-01-08 at 18 32 10-fs8](https://cloud.githubusercontent.com/assets/191754/21751487/dc040e82-d5d0-11e6-8b24-2620bb506686.png)

Are you sure you've pull the latest master branch of the theme?

**Comment by fte378** [comment]
Oops. There was a leftover style.css in my own static area. Don't even remember why this is there.
All worked after removing it.
